import { copyFileSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { arch, platform } from 'node:os'
import { dirname, join, relative, sep } from 'node:path'
import { fileURLToPath } from 'node:url'
import { spawnSync } from 'node:child_process'

const repo = join(dirname(fileURLToPath(import.meta.url)), '..')
const buildDir = join(repo, 'build')
const cargoTarget = join(buildDir, 'cargo', 'map')
const runtimeAssets = join(buildDir, 'runtime-assets')
const catalogOutput = join(repo, 'src', 'catalog.generated.ts')

function run(command, args, options = {}) {
  const result = spawnSync(command, args, {
    cwd: repo,
    stdio: 'inherit',
    shell: options.shell ?? false,
    ...options,
  })
  if (result.error) throw result.error
  if (result.status !== 0) process.exit(result.status ?? 1)
}

function commandExists(command) {
  const checker = platform() === 'win32' ? 'where' : 'which'
  const result = spawnSync(checker, [command], { stdio: 'ignore' })
  return result.status === 0
}

function addDeclared(files, skillRoot, rel) {
  const full = join(skillRoot, rel)
  if (!existsSync(full)) throw new Error(`missing declared asset ${relative(repo, full)}`)
  if (statSync(full).isDirectory()) {
    for (const entry of readdirSync(full)) addDeclared(files, skillRoot, join(rel, entry))
    return
  }
  const key = relative(skillRoot, full).split(sep).join('/')
  files[key] = readFileSync(full).toString('base64')
}

function generateCatalog() {
  const skillsRoot = join(repo, 'skills')
  const catalog = {}
  for (const entry of readdirSync(skillsRoot)) {
    const skillRoot = join(skillsRoot, entry)
    if (!statSync(skillRoot).isDirectory()) continue
    const manifestPath = join(skillRoot, 'jl-skill.json')
    if (!existsSync(manifestPath)) continue
    const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'))
    const files = {}
    const declared = new Set([
      ...(manifest.skill_files ?? []),
      ...(manifest.runtime_files ?? []),
      ...(manifest.instruction_fragment ? [manifest.instruction_fragment] : []),
    ])
    for (const rel of declared) addDeclared(files, skillRoot, rel)
    for (const rel of Object.values(manifest.runtime_artifacts ?? {})) {
      const staged = join(runtimeAssets, entry, rel)
      if (!existsSync(staged)) throw new Error(`missing staged runtime artifact ${entry}/${rel}`)
      files[rel.replaceAll('\\', '/')] = readFileSync(staged).toString('base64')
    }
    catalog[entry] = { manifest, files }
  }
  mkdirSync(dirname(catalogOutput), { recursive: true })
  writeFileSync(catalogOutput, `// Generated by scripts/build.mjs. Do not edit.\nexport const catalog = ${JSON.stringify(catalog, null, 2)} as const\n`)
}

function nodeAtLeast(major, minor) {
  const [haveMajor, haveMinor] = process.versions.node.split('.').map(Number)
  return haveMajor > major || (haveMajor === major && haveMinor >= minor)
}

if (platform() !== 'win32' || arch() !== 'x64') {
  throw new Error('current installer build supports Windows x64 only')
}
if (!nodeAtLeast(20, 19)) {
  throw new Error(`Node 20.19+ is required to build the installer; found ${process.versions.node}`)
}
if (!commandExists('cargo')) throw new Error('cargo is required to build the bundled Map runtime')
if (!existsSync(join(repo, 'node_modules'))) throw new Error('node_modules missing; run npm install first')

mkdirSync(buildDir, { recursive: true })
rmSync(runtimeAssets, { recursive: true, force: true })

run('cargo', [
  'build',
  '--manifest-path', join(repo, 'skills', 'map', 'Cargo.toml'),
  '--release',
  '--target-dir', cargoTarget,
])

const stagedMap = join(runtimeAssets, 'map', 'runtime', 'windows-x64', 'map.exe')
mkdirSync(dirname(stagedMap), { recursive: true })
copyFileSync(join(cargoTarget, 'release', 'map.exe'), stagedMap)
generateCatalog()

const tsdown = join(repo, 'node_modules', '.bin', 'tsdown.cmd')
run(tsdown, [
  'src/jl-skill.ts',
  '--format', 'cjs',
  '--platform', 'node',
  '--target', 'node20',
  '--out-dir', 'build/installer',
  '--clean',
], { shell: true })

const bundle = join(buildDir, 'installer', 'jl-skill.cjs')
if (!existsSync(bundle)) throw new Error(`missing bundled installer ${bundle}`)

const output = join(buildDir, 'jl-skill.exe')
const seaConfig = join(buildDir, 'sea-config.json')
rmSync(output, { force: true })

if (nodeAtLeast(25, 5)) {
  writeFileSync(seaConfig, JSON.stringify({
    main: bundle,
    output,
    disableExperimentalSEAWarning: true,
    useSnapshot: false,
    useCodeCache: false,
  }, null, 2))
  run(process.execPath, ['--build-sea', seaConfig])
} else {
  const blob = join(buildDir, 'jl-skill.blob')
  writeFileSync(seaConfig, JSON.stringify({
    main: bundle,
    output: blob,
    disableExperimentalSEAWarning: true,
    useSnapshot: false,
    useCodeCache: false,
  }, null, 2))
  run(process.execPath, ['--experimental-sea-config', seaConfig])
  copyFileSync(process.execPath, output)
  if (commandExists('signtool')) {
    const remove = spawnSync('signtool', ['remove', '/s', output], { stdio: 'inherit' })
    if (remove.error) throw remove.error
  }
  const postject = join(repo, 'node_modules', '.bin', 'postject.cmd')
  run(postject, [
    output,
    'NODE_SEA_BLOB',
    blob,
    '--sentinel-fuse',
    'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
  ], { shell: true })
}

console.log(`Built ${output}`)
