import { existsSync, readdirSync, readFileSync, statSync, writeFileSync, mkdirSync } from 'node:fs'
import { basename, join, relative, sep } from 'node:path'

const repo = join(import.meta.dir, '..')
const skillsRoot = join(repo, 'skills')
const stagedRuntimeRoot = join(repo, 'build', 'runtime-assets')
const output = join(repo, 'src', 'catalog.generated.ts')
const skillMetaPrefix = 'jl-skills-meta:'

function addDeclared(files: Record<string, string>, skillRoot: string, rel: string): void {
  const full = join(skillRoot, rel)
  if (!existsSync(full)) throw new Error(`missing declared asset ${relative(repo, full)}`)
  if (statSync(full).isDirectory()) {
    for (const entry of readdirSync(full)) addDeclared(files, skillRoot, join(rel, entry))
    return
  }
  const key = relative(skillRoot, full).split(sep).join('/')
  files[key] = readFileSync(full).toString('base64')
}

function validateSkillMetadata(skillRoot: string, manifest: any): void {
  const skillFile = (manifest.skill_files ?? []).find((rel: string) => basename(rel).toLowerCase() === 'skill.md')
  if (!skillFile) throw new Error(`${manifest.name ?? basename(skillRoot)} manifest must include SKILL.md`)

  const text = readFileSync(join(skillRoot, skillFile), 'utf8')
  const line = text.split(/\r?\n/).find((candidate) => candidate.includes(skillMetaPrefix))
  if (!line) throw new Error(`${manifest.name} SKILL.md is missing jl-skills metadata`)
  const marker = line.indexOf(skillMetaPrefix)
  const end = line.lastIndexOf('-->')
  if (marker < 0 || end < marker) throw new Error(`${manifest.name} SKILL.md has malformed jl-skills metadata`)

  let metadata: any
  try {
    metadata = JSON.parse(line.slice(marker + skillMetaPrefix.length, end).trim())
  } catch {
    throw new Error(`${manifest.name} SKILL.md has invalid jl-skills metadata JSON`)
  }
  if (metadata?.name !== manifest.name || metadata?.version !== manifest.version || metadata?.format !== 1) {
    throw new Error(`${manifest.name} SKILL.md metadata must match manifest name/version and format 1`)
  }
}

const catalog: Record<string, { manifest: unknown; files: Record<string, string> }> = {}

for (const entry of readdirSync(skillsRoot)) {
  const skillRoot = join(skillsRoot, entry)
  if (!statSync(skillRoot).isDirectory()) continue
  const manifestPath = join(skillRoot, 'manifest.json')
  if (!existsSync(manifestPath)) continue

  const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'))
  validateSkillMetadata(skillRoot, manifest)
  const files: Record<string, string> = {}
  const declared = new Set<string>([
    ...(manifest.skill_files ?? []),
    ...(manifest.runtime_files ?? []),
    ...Object.keys(manifest.runtime_shared_files ?? {}),
    ...(manifest.instruction_fragment ? [manifest.instruction_fragment] : []),
  ])
  for (const rel of declared) addDeclared(files, skillRoot, rel)

  const runtimeArtifacts = manifest.runtime_artifacts as Record<string, string> | undefined
  for (const rel of Object.values(runtimeArtifacts ?? {})) {
    const staged = join(stagedRuntimeRoot, entry, rel)
    if (!existsSync(staged)) throw new Error(`missing staged runtime artifact ${entry}/${rel}`)
    files[rel.replaceAll('\\', '/')] = readFileSync(staged).toString('base64')
  }

  catalog[entry] = { manifest, files }
}

mkdirSync(join(repo, 'src'), { recursive: true })
writeFileSync(
  output,
  `// Generated by scripts/generate-catalog.ts. Do not edit.\nexport const catalog = ${JSON.stringify(catalog, null, 2)} as const\n`,
)
console.log(`Generated ${output} with ${Object.keys(catalog).length} skill(s).`)
