import { readdirSync, readFileSync, statSync, writeFileSync, mkdirSync } from 'node:fs'
import { join, relative, sep } from 'node:path'

const repo = join(import.meta.dir, '..')
const skillsRoot = join(repo, 'skills')
const output = join(repo, 'src', 'catalog.generated.ts')

function walk(root: string): string[] {
  const out: string[] = []
  for (const entry of readdirSync(root)) {
    const full = join(root, entry)
    if (statSync(full).isDirectory()) out.push(...walk(full))
    else out.push(full)
  }
  return out
}

const catalog: Record<string, { manifest: unknown; files: Record<string, string> }> = {}

for (const entry of readdirSync(skillsRoot)) {
  const skillRoot = join(skillsRoot, entry)
  if (!statSync(skillRoot).isDirectory()) continue
  const manifestPath = join(skillRoot, 'jl-skill.json')
  try {
    const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'))
    const files: Record<string, string> = {}
    for (const path of walk(skillRoot)) {
      const rel = relative(skillRoot, path).split(sep).join('/')
      files[rel] = readFileSync(path).toString('base64')
    }
    catalog[entry] = { manifest, files }
  } catch {
    // Directories without a jl-skill manifest are not installable catalog entries.
  }
}

mkdirSync(join(repo, 'src'), { recursive: true })
writeFileSync(
  output,
  `// Generated by scripts/generate-catalog.ts. Do not edit.\nexport const catalog = ${JSON.stringify(catalog, null, 2)} as const\n`,
)
console.log(`Generated ${output} with ${Object.keys(catalog).length} skill(s).`)
