"""Public CLI entrypoint for the /map prototype."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

import map_agent_query
import map_query
import map_session
import map_state


def command_name(argv: list[str]) -> str | None:
    """Find the top-level command while tolerating --root before it."""
    skip_next = False
    for token in argv:
        if skip_next:
            skip_next = False
            continue
        if token == "--root":
            skip_next = True
            continue
        if token.startswith("--root="):
            continue
        if token.startswith("-"):
            continue
        return token
    return None


def without_command(argv: list[str], command: str) -> list[str]:
    result = list(argv)
    try:
        result.remove(command)
    except ValueError:
        pass
    return result


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="map",
        description="Durable local intent graph for agents and humans",
    )
    parser.add_argument("--root", type=Path, default=Path.cwd(), help="Directory whose .map/ state should be used")
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("init", help="Initialize Map state in this root")
    sub.add_parser("status", help="Show node, relation, and session counts")
    sub.add_parser("list", help="List all graph nodes")

    show = sub.add_parser("show", help="Show one node")
    show.add_argument("id")

    questions = sub.add_parser(
        "questions",
        help="Show the current decision frontier: ready, blocked, and inapplicable questions",
    )
    questions.add_argument("--focus", help="Limit the frontier to this node and its contained descendants")

    sub.add_parser("ideas", help="List parked ideas")

    decide = sub.add_parser("decide", help="Record the answer to an unresolved decision")
    decide.add_argument("id")
    decide.add_argument("value", help="JSON scalar/object/array, or plain text")
    decide.add_argument(
        "--authority",
        choices=map_state.AUTHORITIES,
        default="user",
        help="Provenance of the decision value (default: user)",
    )

    revise = sub.add_parser("revise", help="Replace an existing decided decision while preserving history")
    revise.add_argument("id", help="Current decision to replace")
    revise.add_argument("value", help="New JSON scalar/object/array, or plain text")
    revise.add_argument("--subject", help="Optional replacement subject text")
    revise.add_argument(
        "--new-id",
        help="Optional explicit replacement record ID for import/testing; generated by default",
    )
    revise.add_argument(
        "--authority",
        choices=map_state.AUTHORITIES,
        default="user",
        help="Provenance of the revised decision value (default: user)",
    )

    promote = sub.add_parser("promote", help="Promote a parked idea into active user intent")
    promote.add_argument("id")
    promote.add_argument("--parent", help="Existing intent that should contain the promoted intent")

    add = sub.add_parser("add", help="Add a semantic node")
    add.add_argument("kind", choices=map_state.NODE_KINDS)
    add.add_argument("subject")
    add.add_argument(
        "--id",
        help="Optional explicit record ID for import/testing; generated by default",
    )
    add.add_argument(
        "--state",
        help="Override the kind's normal initial state",
    )
    add.add_argument(
        "--authority",
        choices=map_state.AUTHORITIES,
        help="Provenance; defaults to user except parked ideas, which default to none",
    )
    add.add_argument("--detail")
    add.add_argument("--value")

    edge = sub.add_parser("relate", help="Create a semantic graph relation")
    edge.add_argument("source")
    edge.add_argument("relation", choices=sorted(map_state.RELATIONS))
    edge.add_argument("target")
    edge.add_argument("--note")
    edge.add_argument("--condition", help="JSON condition object; only valid for depends_on")

    history = sub.add_parser("history", help="Show the supersession lineage containing a node")
    history.add_argument("id")

    context = sub.add_parser("context", help="Show compact current-state context for a node or intent")
    context.add_argument("id")

    related = sub.add_parser("related", help="Show all directly related semantic graph neighbors")
    related.add_argument("id")

    sub.add_parser("validate", help="Check structural and semantic graph invariants without mutation")

    search = sub.add_parser("search", help="Search current Map nodes by semantic text fields")
    search.add_argument("query")
    search.add_argument("--limit", type=int, default=10)
    search.add_argument("--include-history", action="store_true", help="Include superseded historical nodes")

    explain = sub.add_parser("explain", help="Show stored graph context supporting one node")
    explain.add_argument("id")

    return parser


def validated_graph(db: Any) -> dict[str, Any]:
    result = map_query.validate_graph(db)
    errors = set(result.get("errors", []))
    errors.update(map_state.semantic_state_errors(map_state.all_nodes(db)))
    result["errors"] = sorted(errors)
    result["ok"] = not result["errors"]
    return result


def main(argv: list[str] | None = None) -> int:
    args_list = list(sys.argv[1:] if argv is None else argv)
    command = command_name(args_list)

    # Session grammar is intentionally left alone for the next design pass.
    if command == map_session.SESSION_COMMAND:
        return map_session.main(without_command(args_list, command))

    args = build_parser().parse_args(args_list)
    root: Path = args.root

    try:
        if args.command == "init":
            map_state.init_map(root)
            return 0

        def run(db: Any):
            if args.command == "status":
                counts = {"nodes": len(map_state.all_nodes(db))}
                for relation in sorted(map_state.RELATIONS):
                    counts[relation] = len(db.select(relation) or [])
                counts["sessions"] = len(db.select("map_session") or [])
                map_state.emit(counts)
            elif args.command == "list":
                map_state.emit(map_state.all_nodes(db))
            elif args.command == "show":
                map_state.emit(map_state.get_node(db, args.id))
            elif args.command == "questions":
                map_state.emit(map_state.compute_frontier(db, args.focus))
            elif args.command == "ideas":
                map_state.emit([
                    node for node in map_state.all_nodes(db)
                    if node.get("kind") == "idea" and node.get("state") == "parked"
                ])
            elif args.command == "decide":
                value = map_state.parse_scalar(args.value)
                map_state.decide_decision(db, args.id, value, authority=args.authority)
                map_state.emit({"ok": True, "decided": args.id, "value": value, **map_state.compute_frontier(db)})
            elif args.command == "revise":
                value = map_state.parse_scalar(args.value)
                result = map_state.revise_decision(
                    db,
                    args.id,
                    value,
                    new_id=args.new_id,
                    subject=args.subject,
                    authority=args.authority,
                )
                map_state.emit({"ok": True, "revision": result, **map_state.compute_frontier(db)})
            elif args.command == "promote":
                promoted = map_state.promote_idea(db, args.id, args.parent)
                map_state.emit({"ok": True, "promoted": args.id, "node": promoted, **map_state.compute_frontier(db)})
            elif args.command == "add":
                value = map_state.parse_scalar(args.value) if args.value is not None else None
                result = map_state.create_node(db, args.id, {
                    "kind": args.kind,
                    "state": args.state,
                    "authority": args.authority,
                    "subject": args.subject,
                    "detail": args.detail,
                    "value": value,
                })
                map_state.emit(result)
            elif args.command == "relate":
                condition = json.loads(args.condition) if args.condition else None
                if condition is not None and args.relation != "depends_on":
                    raise ValueError("--condition is only supported for depends_on")
                map_state.emit(map_state.relate(
                    db,
                    args.source,
                    args.relation,
                    args.target,
                    note=args.note,
                    condition=condition,
                ))
            elif args.command == "history":
                map_state.emit(map_query.history_for(db, args.id))
            elif args.command == "context":
                map_state.emit(map_query.context_for(db, args.id))
            elif args.command == "related":
                map_state.emit(map_query.related_for(db, args.id))
            elif args.command == "validate":
                map_state.emit(validated_graph(db))
            elif args.command == "search":
                map_state.emit(map_agent_query.search_nodes(
                    db,
                    args.query,
                    limit=args.limit,
                    include_history=args.include_history,
                ))
            elif args.command == "explain":
                map_state.emit(map_agent_query.explain_node(db, args.id))
            else:
                raise AssertionError(args.command)

        map_state.command_with_db(root, run)
        return 0
    except Exception as exc:
        print(f"map: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
